### ISSUE TITLE
Rviz2 crashed when attending MotionPlanning plan + Planning Cartesian

### ISSUE THREAD

**Issue by alexlt97** [ros-planning/moveit2_tutorials#111]
### Description

Overview of your issue here.

### Your environment
* ROS Distro: [Foxy]
* OS Version: e.g. Ubuntu 20.04
* Binary build
*

### Steps to reproduce
Following [MoveIt Quickstart in RViz](http://moveit2_tutorials.picknik.ai/doc/quickstart_in_rviz/quickstart_in_rviz_tutorial.html) it crashed when planning cartesian.

### Expected behaviour
It moves as in the tutorial

### Backtrace or Console output

 [Here](https://gist.github.com/alexlt97/2d21d691dd534d079cc04e98c2951950)

**Comment by vatanaksoytezer** [comment]
I can't seem to reproduce this, but having said that the tutorials was not working mainly because of  https://github.com/ros-controls/ros2_controllers/pull/230 and https://github.com/ros-planning/moveit_resources/pull/96.

Cloning ros2_control, ros2_controllers and moveit_resources from source to your workspace should resolve the issue:

```bash
cd ~/ws_moveit2/src
git clone https://github.com/ros-planning/moveit_resources -b ros2 
git clone https://github.com/ros-controls/ros2_controllers -b foxy
git clone https://github.com/ros-controls/ros2_control -b foxy
```

Let me know if this helps.

**Comment by alexlt97** [comment]
Thanks you!
