### ISSUE TITLE
Humble Docker images need to build Humble branch of MTC

### ISSUE THREAD

**Issue by sea-bass** [ros-planning/moveit2_tutorials#741]
Building the Humble version of this repository requires the `humble`, not `ros2`, branch of MTC, since these branches have now diverged mainly due to underscores in class member names.

So, we likely need to bring in variants of the `upstream.repos` file and use the `${ROS_DISTRO}` Dockerfile argument to help manage this.

**Comment by bmaxdk** [comment]
The situation where you need to build Docker images for the Humble branch of the MoveIt Task Constructor (MTC) and that these branches have diverged due to naming conventions, specifically underscores in class member names.

Have you use build arguments in Dockerfile? In the Dockerfile, you can use build arguments (e.g., ${ROS_DISTRO}) to define different behaviors based on the ROS distribution
```docker
ARG ROS_DISTRO=humble

# Conditional logic based on ROS_DISTRO
RUN if [ "${ROS_DISTRO}" = "humble" ]; then \
      git clone -b humble https://github.com/your-org/mtc.git; \
    else \
      git clone -b ros2 https://github.com/your-org/mtc.git; \
    fi

```
