### ISSUE TITLE
moveit2_tutorials demo.launch.py not working

### ISSUE THREAD

**Issue by sjahr** [ros-planning/moveit2_tutorials#821]
### Description

Launch the demo.launch.py file fails probably due to an invalid parameter

### Your environment
* ROS Distro: [Rolling]
* OS Version: Ubuntu 22.04
* Source or Binary build? Source
* If source, which git commit or tag? main https://github.com/ros-planning/moveit2_tutorials/commit/71ee840a50794bbfd35e5b63e80fc633d89840ed

### Steps to reproduce
```
ros2 launch moveit2_tutorials demo.launch.py
```

### Expected behaviour
Demo launches

### Backtrace or Console output

```
^^/ws_moveit_tutorials >>> ros2 launch moveit2_tutorials demo.launch.py                                                                                                                                     11:58:58
[INFO] [launch]: All log files can be found below /home/sebastian/.ros/log/2023-11-30-11-58-59-792639-hedgehog12-180049
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Invalid parameter "isaac_joint_commands"
```

**Comment by dyackzan** [comment]
The main branch of ros2_kortex was recently updated to include some new arguments in the description macros for rendering the kinova and I'm guessing there is now a compatibility issue with the way the kinova is being launched here. I'll investigate, but a short term fix will probably be to check out the commit with hash 740d21b5650a74104fb8c5afb56f7b6f055cdb83 in the ros2_kortex repo (the commit before the kinova macros were updated).

**Comment by dyackzan** [comment]
This breakage is due to the fact that we are pointing to the latest commits on the main branch in ros2_kortex which pass along the "isaac_joint_commands" parameter, but we are using outdated binaries for the robotiq_description package that are not compatible. The latest changes in the robotiq_description repo accept the "isaac_joint_commands" parameter, but the binaries do not have these changes. So we attempt to pass along an "isaac_joint_commands" parameter when loading the gripper in [robotiq_2f_85_macro.urdf.xacro](https://github.com/Kinovarobotics/ros2_kortex/blob/main/kortex_description/grippers/robotiq_2f_85/urdf/robotiq_2f_85_macro.xacro), to the old [robotiq_description](https://github.com/PickNikRobotics/ros2_robotiq_gripper/blob/1ec8f2a9c692d714f5a255795105c63ea127c543/robotiq_description/urdf/robotiq_2f_85_macro.urdf.xacro#L3) macro which does not accept the parameter and throws the error.

**Comment by varun7860** [comment]
It still doesn't work after adding `ros2_robotiq_gripper`. I am encountering error which says 
"By not providing "Findserial.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "serial", but
  CMake did not find one."
  
  How to solve this?

**Comment by mataoh92** [comment]
Same issue occurrs in the following environment.
- ROS Distro: [Humble]
- OS Version: Ubuntu 22.04
- Source or Binary build? Source

**Comment by Abishalini** [comment]
@varun7860 You will have to clone the serial package to your workspace - https://github.com/tylerjw/serial/tree/ros2
Make sure you use the ros2 branch.

**Comment by Abishalini** [comment]
@varun7860 I have updated the `.repos` file so `ros2_robotiq_gripper` and `serial` will be cloned to your workspace - https://github.com/ros-planning/moveit2_tutorials/pull/826
Run `vcs import src < src/moveit2_tutorials/moveit2_tutorials.repos` and build again.

**Comment by dyackzan** [comment]
Closing since this is resolved by https://github.com/ros-planning/moveit2_tutorials/pull/826
